name: DevOps Challenge
on:
  push:
    branches:
      - main
env:
  DOCKERHUB_U: ${{ secrets.DOCKERHUB_U }}
  DOCKERHUB_P: ${{ secrets.DOCKERHUB_P }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  REGISTRY: ${{ secrets.DOCKERHUB_U }}
  IMAGE_NAME: flask
  AWS_REGION: us-east-1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_U }}
          password: ${{ secrets.DOCKERHUB_P }}
      - name: Image build and push
        uses: docker/build-push-action@v2
        with:
          context: ./flask
          push: true
          dockerfile: Dockerfile
          tags: ${{ env.DOCKERHUB_U }}/flask:${{ github.run.number }}