name: DevOps Challenge
on:
  push:
    branches:
      - main
env:
  DOCKERHUB_U: ${{ secrets.DOCKERHUB_U }}
  DOCKERHUB_P: ${{ secrets.DOCKERHUB_P }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_REGION: us-east-1
  TAG: ${{ github.run.number }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_U }}
          password: ${{ secrets.DOCKERHUB_P }}
      - name: Image build and push
        uses: docker/build-push-action@v2
        with:
          context: ./flask
          push: true
          dockerfile: Dockerfile
          tags: ${{ env.DOCKERHUB_U }}/flask:${{ env.TAG }}


  # deploy-tf:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2.5.0
  #     - name: terrafrom install 
  #       uses: hashicorp/setup-terraform@v2.0.2
  #     - name: Configure AWS Credentials Action For GitHub Actions
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ env.AWS_REGION }}

  #     - name: Checking exsistance of tf files
  #       run: ls -la 
  #     - name: terraform apply
  #       run: |
  #         terraform init
  #         terraform plan
  #         terraform apply --auto-approve
